volumes:
  postgres-data:


services:
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # MAVEN_OPTS: -Dmaven.build.cache.enabled=true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_HTTP_ENABLED: true
      # KC_LOG_LEVEL: DEBUG
      # KC_HOSTNAME_STRICT: false
      # KC_HEALTH_ENABLED: true
      # KC_METRICS_ENABLED: true

      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432

    depends_on:
      - db

    ports:
      - "8080:8080"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in keycloak container
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: keycloak
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_SERVER_JSON_FILE: "/tmp/servers.json"
    volumes:
      - ./pgadmin-servers.json:/tmp/servers.json:ro

    depends_on:
      - db
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'db:5432:*:keycloak:keycloak' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: on-failure
    ports:
      - "8543:80"
